# Generated by Django 5.2.4 on 2025-07-04 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftwapp', '0002_alter_category_parent_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='category',
        ),
        migrations.AddField(
            model_name='word',
            name='subcategory',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='ftwapp.subcategory'),
            preserve_default=False,
        ),
    ]
