# Generated by Django 5.2.4 on 2025-07-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftwapp', '0003_remove_word_category_word_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
