# Generated by Django 5.2.4 on 2025-07-15 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftwapp', '0006_alter_subcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ftwapp.category'),
        ),
        migrations.AlterField(
            model_name='word',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ftwapp.subcategory'),
        ),
    ]
