# Generated by Django 5.2.4 on 2025-07-15 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftwapp', '0007_word_category_alter_word_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='ftwapp.category'),
        ),
        migrations.AlterField(
            model_name='word',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='ftwapp.subcategory'),
        ),
    ]
