# Generated by Django 5.2.4 on 2025-07-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftwapp', '0008_alter_word_category_alter_word_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
